// Hand-written declaration for the drizzle-kit-generated migrations.js
// (regenerated by `npm run db:generate`; this file is stable).
declare const migrations: {
  journal: { entries: { idx: number; when: number; tag: string; breakpoints: boolean }[] };
  migrations: Record<string, string>;
};
export default migrations;
